task: 'ts_classification' # time series classification

dataset: None

feature_generator: None

error_correction: False

n_ecm_cycles: 3

ensemble_algorithm: None

launches: 1

fedot_params:
  {
    'problem': 'classification',
    'seed': 42,
    'timeout': 15,
    'max_depth': 10,
    'max_arity': 4,
    'cv_folds': 2,
    'logging_level': 20,
    'n_jobs': -1
  }
