task: 'ts_classification' # time series classification

dataset: None

strategy: 'fedot_preset'

model_params:
  {
    'problem': 'classification',
    'seed': 42,
    'timeout': 15,
    'max_depth': 10,
    'max_arity': 4,
    'cv_folds': 2,
    'logging_level': 20,
    'n_jobs': -1
  }
