feature_generator: [
'recurrence'
]

error_correction: False
ensemble_algorithm: False
n_ecm_cycles: 2

use_cache: False
launches: 1

datasets_list: [
  #'ElectricDevices',
  'Lightning7',
]

feature_generator_params: {
  'recurrence':
    {
      'window_mode': False,
      'image_mode':True
    }
}

model_params: {
    'model': 'SimpleConvNet2',
    'dataloader_params':{'batch_size':10},
    'model_params': {},
    'optimizer_params': {},
    'loss_params': {},
    'metric': 'f1',
    'epoch':5,
    'summary_per_class': True,
    'optimization_method': {
      'svd_parameters': {
        'decomposing_mode': 'channel',
        'orthogonal_loss_factor': 100,
        'hoer_loss_factor': 0.0001,
        'energy_thresholds': [
            0.1, 0.3, 0.5, 0.7, 0.9,
            0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
            0.992, 0.994, 0.996, 0.998, 0.999,
            0.9999, 1
        ],
        'finetuning_epochs': 5
      },
      'sfp_parameters': { 'pruning_ratio': 0.7 },
      'mode': 'SVD'
    }
              }

task: 'TSCImage'
logger: 'logger'