feature_generator: [
'recurrence'
]

error_correction: False
ensemble_algorithm: False
n_ecm_cycles: 2

use_cache: False
launches: 1

datasets_list: [
  'ElectricDevices',
  'Lightning7',
]

feature_generator_params: {
  'recurrence':
    {
      'window_mode': False,
      'image_mode':True
    }
}

model_params: {
    'model': 'ResNet50one',
    'dataloader_params':{'batch_size':100},
    'model_params': {},
    'optimizer_params': {},
    'loss_params': {},
    'metric': 'f1',
    'epoch':50,
    'summary_per_class': True,
    'optimization_method': {
      'svd_parameters': {
        'decomposing_mode': 'channel',
        'orthogonal_loss_factor': 100,
        'hoer_loss_factor': 0.001,
        'energy_thresholds': [
            0.1,
            0.6,
            0.9,
            0.95,
            0.99,
            1.0

        ],
        'finetuning_epochs': 15
      },
      'sfp_parameters': { 'pruning_ratio': 0.7 },
      'mode': 'SVD'
    }
              }

task: 'TSCImage'
logger: 'logger'