feature_generator: [
'quantile'
]

error_correction: False
n_ecm_cycles: 3
use_cache: False
ensemble_algorithm: False

datasets_list: ['Lightning7']

launches: 1

feature_generator_params: {
  'window_quantile':
    {
      'window_mode': True,
    },
  'spectral':
    {
      'window_sizes': {
        'ItalyPowerDemand': [3, 6, 9],
        'Earthquakes': [48],
        'Beef': [100]
      },
    },
  'wavelet':
    {
      'wavelet_types': ['sym10']
    }
}

fedot_params:
  {
    'problem': 'classification',
    'seed': 42,
    'timeout': 1,
    'max_depth': 10,
    'max_arity': 4,
    'cv_folds': 2,
    'logging_level': 20,
    'n_jobs': 2
  }
task: 'ts_classification' # time series classification