feature_generator: [
'quantile',
'spectral',
]
error_correction: False

datasets_list: [
  'Earthquakes',
  'ItalyPowerDemand',
  'Beef'
]

'launches': 1

feature_generator_params: {
  'quantile':
    {
      'window_mode': False,
    },
  'spectral':
    {
      'window_sizes': {
        'ItalyPowerDemand': [3, 6, 9],
        'Earthquakes': [48],
        'Beef': [100]
      },
    }
}

fedot_params:
  {
    'problem': 'classification',
    'seed': 42,
    'timeout': 15,
    'max_depth': 10,
    'max_arity': 4,
    'cv_folds': 2,
    'stopping_after_n_generation': 20,
    'logging_level': 20,
    'n_jobs': 4
  }
task: 'classification'
logger: 'logger'