feature_generator: [
'wavelet'
]
error_correction: False
n_ecm_cycles: 3
datasets_list: [
  #'Lightning7',
  'ElectricDevices'
]

launches: 1


feature_generator_params: {
  'quantile':
    {
      'window_mode': False,
    },
  'spectral':
    {
      'window_sizes': {
        'ItalyPowerDemand': [3, 6, 9],
        'Earthquakes': [48],
        'Beef': [100]
      },
    },
  'wavelet':
    {
      'wavelet_types': ['sym10']
    }
}

fedot_params:
  {
    'problem': 'classification',
    'seed': 42,
    'timeout': 30,
    'max_depth': 10,
    'max_arity': 4,
    'cv_folds': 3,
    'metric':'f1',
    'stopping_after_n_generation': 10,
    'logging_level': 20,
    'n_jobs': 4
  }
task: 'classification'
logger: 'logger'