feature_generator: [
#        'window_quantile',
#        'quantile',
#        'wavelet',
        'spectral',
        'spectral_window'
]

datasets_list: [
  'ItalyPowerDemand',
  'Lightning7',

  ]
'launches': 1
feature_generator_params: {
  'window_quantile':
    {
      'window_mode': True,
      'launches': 2
    },

  'quantile':
    { 'window_mode': False,
      'launches': 1
    },
  'wavelet':
    { 'feature_generanor_dict':
        {
          'ElectricDevices': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'EthanolLevel': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'Earthquakes': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'Lightning7': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'Beef': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'ItalyPowerDemand': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'Haptics': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'ShapesAll': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'FordA': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'FordB': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
          'PowerCons': [ 'db5', 'sym5', 'coif5', 'bior2.4' ],
        },
      'launches': 1,
      'list_of_dataset': ['ItalyPowerDemand']
    },
  'spectral_window':
    {
      'feature_generanor_dict': {
        'ItalyPowerDemand': [ 3, 6, 9 ],
        'Herring': [ 48, 128, 170 ],
        'Haptics': [ 110, 220, 330 ],
        'DodgerLoopDay': [ 28, 56, 84 ],
        'Earthquakes': [ 48, 128, 170 ],
        'FordA': [ 50, 100, 150 ],
        'FordB': [ 50, 100, 150 ],
        'Plane': [ 14, 28, 42 ],
        'Trace': [ 27, 54, 81 ],
        'Lightning7': [ 32, 64, 96 ],
        'EthanolLevel': [ 170, 340, 510 ],
        'ElectricDevices': [ 10, 20, 30 ],
        'Beef': [ 100, 150, 200 ],
        'PowerCons': [ 30, 45, 60 ],
        'ShapesAll': [ 100, 150, 200 ]
      },
      'launches': 1,
      'window_mode': True,
      'list_of_dataset': [ 'ItalyPowerDemand' ]
    },
  'spectral':
    {
      'feature_generanor_dict': {
        'ItalyPowerDemand': [ 3, 6, 9 ],
        'Herring': [ 48, 128, 170 ],
        'Haptics': [ 110, 220, 330 ],
        'DodgerLoopDay': [ 28, 56, 84 ],
        'Earthquakes': [ 48, 128, 170 ],
        'FordA': [ 50, 100, 150 ],
        'FordB': [ 50, 100, 150 ],
        'Plane': [ 14, 28, 42 ],
        'Trace': [ 27, 54, 81 ],
        'Lightning7': [ 32, 64, 96 ],
        'EthanolLevel': [ 170, 340, 510 ],
        'ElectricDevices': [ 10, 20, 30 ],
        'Beef': [ 100, 150, 200 ],
        'PowerCons': [ 30, 45, 60 ],
        'ShapesAll': [ 100, 150, 200 ]
      },
      'launches': 1,
      'list_of_dataset': [ 'ItalyPowerDemand' ]
    },
  'topological': {
    topological_params:
      {
        'max_simplex_dim': 2,
        'epsilon': 100,
        'persistance_params': None,
        'window_length': 6
      },
    'launches': 1
  }
}
fedot_params:
  {
  'problem': 'classification',
  'seed': 14,
  'timeout': 2,
  'composer_params': {
                      'max_depth': 10,
                      'max_arity': 4,
                      'cv_folds': 3,
                      'stopping_after_n_generation': 20
                      },
  'verbose_level': 3,
  'n_jobs': 6
}
task: 'classification'
logger: 'logger'