feature_generator: [
#      'window_quantile',
  #    'quantile',
  #      'spectral_window',
  #    'spectral',
  #      'wavelet',
'topological'

  #    ожидание:
  #    'quantile_window_50_no_means'+'spectral_window50_no_periodic'+'wavelet_biortogonal',

  #    реальность:
  #  'ensemble: quantile wavelet window_quantile spectral_window'
]

datasets_list: [
  'Lightning7',
  #    'EthanolLevel',
  #      'Beef',
  #      'Wafer'
]

'launches': 1

feature_generator_params: {
  'window_quantile':
    {
      'window_mode': True,
      'launches': 1
    },

  'quantile':
    { 'window_mode': False,
      'launches': 1,
    },
  'wavelet':
    { 'feature_generator_dict':
        {
          'wavelet_types': [ 'db5', 'sym5', 'coif5', 'bior2.4' ]
        },
      'launches': 1,
    },
  'spectral_window':
    {
      'feature_generator_dict': {
        'ItalyPowerDemand': [ 3, 6, 9 ],
        'Herring': [ 48, 128, 170 ],
        'Haptics': [ 110, 220, 330 ],
        'DodgerLoopDay': [ 28, 56, 84 ],
        'Earthquakes': [ 48, 128, 170 ],
        'FordA': [ 50, 100, 150 ],
        'FordB': [ 50, 100, 150 ],
        'Plane': [ 14, 28, 42 ],
        'Trace': [ 27, 54, 81 ],
        'Lightning7': [ 32, 64, 96 ],
        'EthanolLevel': [ 170, 340, 510 ],
        'ElectricDevices': [ 10, 20, 30 ],
        'Beef': [ 100, 150, 200 ],
        'PowerCons': [ 30, 45, 60 ],
        'ShapesAll': [ 100, 150, 200 ],
        'Wafer': [ 100, 150, 200 ]
      },
      'launches': 1,
      'window_mode': True,

    },
  'spectral':
    {
      'feature_generator_dict': {
        'ItalyPowerDemand': [ 3, 6, 9 ],
        'Herring': [ 48, 128, 170 ],
        'Haptics': [ 110, 220, 330 ],
        'DodgerLoopDay': [ 28, 56, 84 ],
        'Earthquakes': [ 48, 128, 170 ],
        'FordA': [ 50, 100, 150 ],
        'FordB': [ 50, 100, 150 ],
        'Plane': [ 14, 28, 42 ],
        'Trace': [ 27, 54, 81 ],
        'Lightning7': [ 32, 64, 96 ],
        'EthanolLevel': [ 170, 340, 510 ],
        'ElectricDevices': [ 10, 20, 30 ],
        'Beef': [ 100, 150, 200 ],
        'PowerCons': [ 30, 45, 60 ],
        'ShapesAll': [ 100, 150, 200 ],
        'Wafer': [ 10, 30, 40 ]
      },
      'launches': 1,

    },
  'topological': {
    topological_params:
      {
        'max_simplex_dim': 2,
        'epsilon': 100,
        'persistance_params': None,
        'window_length': 6
      },

    'launches': 1,

  },
  'ensemble': {
    'list_of_generators': { }
  }
}
fedot_params:
  {
    'problem': 'classification',
    'seed': 14,
    'timeout': 1,
    'composer_params': {
      'max_depth': 10,
      'max_arity': 4,
      'cv_folds': 2,
      'stopping_after_n_generation': 20
    },
    'verbose_level': 3,
    'n_jobs': 2
  }
task: 'classification'
logger: 'logger'