name: Fix PEP 8 Style

on:
  pull_request:
    branches: [ main ]

jobs:
  fix_pep8:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install autopep8
        run: pip install --upgrade autopep8

      - name: Fix PEP 8 style violations
        run: autopep8 --in-place --recursive ./fedot_ind ./tests

      - name: Checkout PR
        env:
            GITHUB_TOKEN: ${{ secrets.PEP8_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          run:
            git add .
            git commit -m "Fix PEP 8 style violations"
            git push origin ${{ github.event.pull_request.head.ref }}
