name: autopep8
on: pull_request
jobs:
  autopep8:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PEP8_TOKEN }}
          ref: ${{ github.head_ref }}
      - name: Install autoflake
        run: pip install autoflake
      - name: Remove unused variables and imports
        run: autoflake --in-place --remove-all-unused-imports --remove-unused-variables --recursive .
      - name: autopep8
        id: autopep8
        uses: peter-evans/autopep8@v2
        with:
          args: --exit-code --recursive --in-place --max-line-length 120 --experimental  --aggressive --aggressive .
      - name: Commit autopep8 changes
        if: steps.autopep8.outputs.exit-code == 2
        run: |
          git config --global user.name 'autopep8 bot'
          git config --global user.email 'autopep8bot@users.noreply.github.com'
          git commit -am "Automated autopep8 fixes"
          git push